steps:
- name: 'gcr.io/cloud-builders/docker'
  timeout: 21600s
  args: [ 'build', '-t', 'gcr.io/qwiklabs-gcp-03-48657acae373/dockerfile', '.' ]
  timeout: 21600s
timeout: 21600s

options:
  pool:
    name: 'projects/qwiklabs-gcp-03-48657acae373/locations/asia-southeast2/workerPools/5555555555'
